---
linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - gosec
    - gocritic
    - importas
    - prealloc
    - revive
    - misspell
    - stylecheck
    - tparallel
    - unconvert
    - unused
    - whitespace
output:
  uniq-by-line: false
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  timeout: 10m
linters-settings:
  stylecheck:
    checks: ["all", "-ST1003"]
  revive:
    rules:
      - name: var-naming
        disabled: true
        
